
name: Test Mapbox Navigation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:

    - name: Install helpers
      run: gem install xcpretty

    - name: Checkout mapbox-navigation-ios
      uses: actions/checkout@v3
      # with:
      #   path: main
    
    - name: Test on iOS 12
      run: xcodebuild -scheme MapboxNavigation test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0' | xcpretty

    - name: Test on iOS 13
      run: xcodebuild -scheme MapboxNavigation test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' | xcpretty

    - name: Test on iOS 14
      run: xcodebuild -scheme MapboxNavigation test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.0' | xcpretty
    
    - name: Test on iOS 15
      run: xcodebuild -scheme MapboxNavigation test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' | xcpretty

    - name: Test on iOS 16
      run: xcodebuild -scheme MapboxNavigation test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' | xcpretty
